/**
 * Copies the Hancom-bundled TTFs that the GEPA house style uses into public/fonts
 * (gitignored; local preview only) and generates app/fonts.css with @font-face
 * declarations whose family names match the font names inside the HWPX files.
 *
 * Usage: pnpm tsx scripts/setup-fonts.ts
 */
import { existsSync, mkdirSync, copyFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, basename } from "node:path";
import { homedir } from "node:os";

/**
 * Where the Hancom fonts live per OS. macOS: inside the app bundle. Windows: the 한컴오피스
 * install folder (HNC\…\Fonts or …\TTF) and the system font folders. Linux: ~/.fonts, /usr/share/fonts.
 * Files are matched by name (case-insensitive) anywhere below these roots, so the exact
 * sub-folder layout of a given 한컴오피스 version does not matter.
 */
const FONT_ROOTS: string[] = (() => {
  const env = process.env;
  if (process.platform === "win32")
    return [
      ...[env.ProgramFiles, env["ProgramFiles(x86)"]].filter(Boolean).map((r) => join(r as string, "HNC")),
      ...[env.ProgramFiles, env["ProgramFiles(x86)"]].filter(Boolean).map((r) => join(r as string, "Hnc")),
      join(env.SystemRoot ?? "C:\\Windows", "Fonts"),
      env.LOCALAPPDATA ? join(env.LOCALAPPDATA, "Microsoft", "Windows", "Fonts") : "",
    ].filter(Boolean);
  if (process.platform === "darwin") return ["/Applications/Hancom Office HWP.app/Contents/Resources/Hnc/Shared/TTF", join(homedir(), "Library", "Fonts"), "/Library/Fonts"];
  return [join(homedir(), ".fonts"), join(homedir(), ".local", "share", "fonts"), "/usr/share/fonts", "/usr/local/share/fonts"];
})();
const HANCOM = FONT_ROOTS[0];

/** Find a font file by name below the roots (depth-limited walk; first hit wins). */
function findFont(fileName: string): string | null {
  const want = fileName.toLowerCase();
  const walk = (dir: string, depth: number): string | null => {
    if (depth > 6 || !existsSync(dir)) return null;
    let entries: string[];
    try {
      entries = readdirSync(dir);
    } catch {
      return null;
    }
    for (const e of entries) {
      const p = join(dir, e);
      let st;
      try {
        st = statSync(p);
      } catch {
        continue;
      }
      if (st.isFile() && e.toLowerCase() === want) return p;
    }
    for (const e of entries) {
      const p = join(dir, e);
      try {
        if (statSync(p).isDirectory()) {
          const r = walk(p, depth + 1);
          if (r) return r;
        }
      } catch {
        /* skip */
      }
    }
    return null;
  };
  for (const root of FONT_ROOTS) {
    const r = walk(root, 0);
    if (r) return r;
  }
  return null;
}
const OUT = join(process.cwd(), "public", "fonts");

// family (as written in HWPX <hh:font face="…">) → source file inside the Hancom bundle
const FONTS: { family: string; file: string; src: string; weight?: number }[] = [
  { family: "휴먼명조", file: "HMKMM.ttf", src: "Hwp/HMKMM.TTF" },
  { family: "HY헤드라인M", file: "H2HDRM.ttf", src: "All/H2HDRM.TTF" },
  { family: "맑은 고딕", file: "malgun.ttf", src: "Install/malgun.ttf" },
  { family: "굴림", file: "Gulim.ttf", src: "Install/Gulim.TTF" },
  { family: "한컴돋움", file: "HDotum.ttf", src: "All/HDotum.TTF" },
  { family: "한컴바탕", file: "HBatang.ttf", src: "All/HBatang.TTF" },
  { family: "HY견고딕", file: "HYGTRE.ttf", src: "Hwp/HYGTRE.TTF" },
];

// Fonts used by the references that are NOT in the bundle → CSS fallback aliases
const ALIASES: { family: string; fallback: string }[] = [
  { family: "한양중고딕", fallback: "HY견고딕" },
  { family: "돋움", fallback: "한컴돋움" },
  { family: "HCI Poppy", fallback: "휴먼명조" },
  { family: "HY중고딕", fallback: "HY견고딕" },
  { family: "함초롬바탕", fallback: "한컴바탕" },
  { family: "함초롬돋움", fallback: "한컴돋움" },
];

mkdirSync(OUT, { recursive: true });
const css: string[] = ["/* generated by scripts/setup-fonts.ts — do not edit */"];
const copied: string[] = [];
const missing: string[] = [];

for (const f of FONTS) {
  const direct = join(HANCOM, f.src);
  const src = existsSync(direct) ? direct : findFont(basename(f.src));
  if (!src) {
    missing.push(`${f.family} (${basename(f.src)} — 검색 경로: ${FONT_ROOTS.join(", ")})`);
    continue;
  }
  copyFileSync(src, join(OUT, f.file));
  copied.push(f.family);
  css.push(
    `@font-face { font-family: "${f.family}"; src: url("/fonts/${f.file}") format("truetype"); font-weight: 100 900; font-display: swap; }`,
  );
}
for (const a of ALIASES) {
  css.push(
    `@font-face { font-family: "${a.family}"; src: local("${a.fallback}"), url("/fonts/${FONTS.find((f) => f.family === a.fallback)?.file ?? ""}") format("truetype"); font-display: swap; }`,
  );
}
css.push(`
:root {
  --font-heading: "HY헤드라인M", "Noto Sans KR", sans-serif;
  --font-body: "휴먼명조", "HCI Poppy", "Noto Serif KR", serif;
  --font-table: "맑은 고딕", "Noto Sans KR", sans-serif;
  --font-note: "한양중고딕", "HY견고딕", "Noto Sans KR", sans-serif;
  --font-approval: "돋움", "한컴돋움", "Noto Sans KR", sans-serif;
}`);

writeFileSync(join(process.cwd(), "app", "fonts.css"), css.join("\n") + "\n");
writeFileSync(
  join(OUT, "LICENSE-NOTE.md"),
  `# Font files in this directory

These TTF files are copied by \`scripts/setup-fonts.ts\` from the locally installed
Hancom Office HWP bundle (\`${HANCOM}\`) purely so the in-browser preview and the
rhwp SVG/PDF renderer on THIS machine can show the same fonts Hancom uses.

They are proprietary (Hancom / HanYang / Microsoft). They are gitignored, must not be
redistributed, and the generated HWPX files never embed them (\`isEmbedded="0"\`).
When the copies are absent the app falls back to Noto Sans KR / Noto Serif KR.
`,
);
console.log("copied:", copied.join(", "));
if (missing.length) console.log("missing (fallbacks used):", missing.join("; "));
console.log("wrote app/fonts.css and public/fonts/LICENSE-NOTE.md");
