/**
 * Copies the Hancom-bundled TTFs that the GEPA house style uses into public/fonts
 * (gitignored; local preview only) and generates app/fonts.css with @font-face
 * declarations whose family names match the font names inside the HWPX files.
 *
 * Usage: pnpm tsx scripts/setup-fonts.ts
 */
import { existsSync, mkdirSync, copyFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const HANCOM = "/Applications/Hancom Office HWP.app/Contents/Resources/Hnc/Shared/TTF";
const OUT = join(process.cwd(), "public", "fonts");

// family (as written in HWPX <hh:font face="…">) → source file inside the Hancom bundle
const FONTS: { family: string; file: string; src: string; weight?: number }[] = [
  { family: "휴먼명조", file: "HMKMM.ttf", src: "Hwp/HMKMM.TTF" },
  { family: "HY헤드라인M", file: "H2HDRM.ttf", src: "All/H2HDRM.TTF" },
  { family: "맑은 고딕", file: "malgun.ttf", src: "Install/malgun.ttf" },
  { family: "굴림", file: "Gulim.ttf", src: "Install/Gulim.TTF" },
  { family: "한컴돋움", file: "HDotum.ttf", src: "All/HDotum.TTF" },
  { family: "한컴바탕", file: "HBatang.ttf", src: "All/HBatang.TTF" },
  { family: "HY견고딕", file: "HYGTRE.ttf", src: "Hwp/HYGTRE.TTF" },
];

// Fonts used by the references that are NOT in the bundle → CSS fallback aliases
const ALIASES: { family: string; fallback: string }[] = [
  { family: "한양중고딕", fallback: "HY견고딕" },
  { family: "돋움", fallback: "한컴돋움" },
  { family: "HCI Poppy", fallback: "휴먼명조" },
  { family: "HY중고딕", fallback: "HY견고딕" },
  { family: "함초롬바탕", fallback: "한컴바탕" },
  { family: "함초롬돋움", fallback: "한컴돋움" },
];

mkdirSync(OUT, { recursive: true });
const css: string[] = ["/* generated by scripts/setup-fonts.ts — do not edit */"];
const copied: string[] = [];
const missing: string[] = [];

for (const f of FONTS) {
  const src = join(HANCOM, f.src);
  if (!existsSync(src)) {
    missing.push(`${f.family} (${src})`);
    continue;
  }
  copyFileSync(src, join(OUT, f.file));
  copied.push(f.family);
  css.push(
    `@font-face { font-family: "${f.family}"; src: url("/fonts/${f.file}") format("truetype"); font-weight: 100 900; font-display: swap; }`,
  );
}
for (const a of ALIASES) {
  css.push(
    `@font-face { font-family: "${a.family}"; src: local("${a.fallback}"), url("/fonts/${FONTS.find((f) => f.family === a.fallback)?.file ?? ""}") format("truetype"); font-display: swap; }`,
  );
}
css.push(`
:root {
  --font-heading: "HY헤드라인M", "Noto Sans KR", sans-serif;
  --font-body: "휴먼명조", "HCI Poppy", "Noto Serif KR", serif;
  --font-table: "맑은 고딕", "Noto Sans KR", sans-serif;
  --font-note: "한양중고딕", "HY견고딕", "Noto Sans KR", sans-serif;
  --font-approval: "돋움", "한컴돋움", "Noto Sans KR", sans-serif;
}`);

writeFileSync(join(process.cwd(), "app", "fonts.css"), css.join("\n") + "\n");
writeFileSync(
  join(OUT, "LICENSE-NOTE.md"),
  `# Font files in this directory

These TTF files are copied by \`scripts/setup-fonts.ts\` from the locally installed
Hancom Office HWP bundle (\`${HANCOM}\`) purely so the in-browser preview and the
rhwp SVG/PDF renderer on THIS machine can show the same fonts Hancom uses.

They are proprietary (Hancom / HanYang / Microsoft). They are gitignored, must not be
redistributed, and the generated HWPX files never embed them (\`isEmbedded="0"\`).
When the copies are absent the app falls back to Noto Sans KR / Noto Serif KR.
`,
);
console.log("copied:", copied.join(", "));
if (missing.length) console.log("missing (fallbacks used):", missing.join("; "));
console.log("wrote app/fonts.css and public/fonts/LICENSE-NOTE.md");
